"""
Portfolio tool server.

Stands in for the bank's book-of-record system. In production this would be
a read-only adapter over a custody/CRM API; here it reads the synthetic JSON
generated by data/generate_data.py. The interface is what matters, and the
agents cannot tell the difference.
"""

from __future__ import annotations

import json
from functools import lru_cache
from typing import Any

from config import settings
from mcp_layer.protocol import ToolResult
from mcp_layer.registry import ToolServer

server = ToolServer(
    name="portfolio",
    description="Read-only access to synthetic client profiles, holdings and performance.",
)


@lru_cache(maxsize=1)
def _load() -> tuple[dict[str, dict], dict[str, dict]]:
    if not settings.clients_path.exists():
        raise FileNotFoundError(
            f"{settings.clients_path} not found. Run: python data/generate_data.py"
        )
    clients_raw = json.loads(settings.clients_path.read_text())
    instruments_raw = json.loads((settings.clients_path.parent / "instruments.json").read_text())
    clients = {c["client_id"]: c for c in clients_raw["clients"]}
    instruments = {i["instrument_id"]: i for i in instruments_raw["instruments"]}
    return clients, instruments


def get_client_record(client_id: str) -> dict[str, Any] | None:
    clients, _ = _load()
    return clients.get(str(client_id).strip().lstrip("#"))


def get_instrument(instrument_id: str) -> dict[str, Any] | None:
    _, instruments = _load()
    return instruments.get(str(instrument_id).strip().upper())


def all_instruments() -> list[dict[str, Any]]:
    _, instruments = _load()
    return list(instruments.values())


@server.tool(
    name="portfolio.get_client_profile",
    description=(
        "Fetch a synthetic client's profile: risk profile, investor classification, horizon, "
        "liquidity needs, ESG mandate, objectives, constraints and suitability review date."
    ),
    input_schema={
        "type": "object",
        "properties": {
            "client_id": {"type": "string", "description": "Client reference, e.g. '4521'"},
        },
        "required": ["client_id"],
        "additionalProperties": False,
    },
)
def get_client_profile(args: dict[str, Any]) -> ToolResult:
    client = get_client_record(args["client_id"])
    if client is None:
        return ToolResult.error(f"No client with id '{args['client_id']}'")

    profile = {
        "client_id": client["client_id"],
        "name": client["name"],
        "data_notice": client["data_notice"],
        "segment": client["segment"],
        "domicile": client["domicile"],
        "adviser": client["adviser"],
        "risk_profile": client["risk_profile"],
        "investor_classification": client["investor_classification"],
        "investment_horizon_years": client["investment_horizon_years"],
        "liquidity_needs": client["liquidity_needs"],
        "esg_mandate": client["esg_mandate"],
        "esg_exclusions": client["esg_exclusions"],
        "last_suitability_review": client["last_suitability_review"],
        "next_meeting": client["next_meeting"],
        "objectives": client["objectives"],
        "constraints": client["constraints"],
        "adviser_notes": client["adviser_notes"],
    }
    summary = (
        f"{client['name']}, {client['risk_profile']} profile, "
        f"{client['investor_classification']}, {client['investment_horizon_years']}y horizon, "
        f"{client['liquidity_needs'].lower()} liquidity needs."
    )
    return ToolResult.ok(profile, summary)


@server.tool(
    name="portfolio.get_holdings",
    description=(
        "Fetch a synthetic client's current holdings, weights, valuations, performance and "
        "portfolio-level risk metrics."
    ),
    input_schema={
        "type": "object",
        "properties": {
            "client_id": {"type": "string", "description": "Client reference, e.g. '4521'"},
        },
        "required": ["client_id"],
        "additionalProperties": False,
    },
)
def get_holdings(args: dict[str, Any]) -> ToolResult:
    client = get_client_record(args["client_id"])
    if client is None:
        return ToolResult.error(f"No client with id '{args['client_id']}'")

    portfolio = client["portfolio"]
    performance = client["performance"]
    payload = {
        "client_id": client["client_id"],
        "as_of": portfolio["as_of"],
        "total_value_gbp": portfolio["total_value_gbp"],
        "currency": portfolio["currency"],
        "holdings": portfolio["holdings"],
        "largest_position_pct": portfolio["largest_position_pct"],
        "cash_pct": portfolio["cash_pct"],
        "weighted_risk_rating": portfolio["weighted_risk_rating"],
        "performance": performance,
    }
    top = max(portfolio["holdings"], key=lambda h: h["weight_pct"])
    summary = (
        f"£{portfolio['total_value_gbp']:,.0f} across {len(portfolio['holdings'])} positions. "
        f"Largest: {top['name']} at {top['weight_pct']}%. "
        f"YTD {performance['ytd_return_pct']}% "
        f"({performance['vs_benchmark_ytd_pct']:+.2f}% vs benchmark)."
    )
    return ToolResult.ok(payload, summary)


@server.tool(
    name="portfolio.list_clients",
    description="List all synthetic client ids with names and risk profiles.",
    input_schema={"type": "object", "properties": {}, "additionalProperties": False},
)
def list_clients(_args: dict[str, Any]) -> ToolResult:
    clients, _ = _load()
    rows = [
        {
            "client_id": c["client_id"],
            "name": c["name"],
            "risk_profile": c["risk_profile"],
            "next_meeting": c["next_meeting"],
        }
        for c in clients.values()
    ]
    return ToolResult.ok({"clients": rows}, f"{len(rows)} synthetic clients on file.")


@server.tool(
    name="portfolio.lookup_instrument",
    description=(
        "Look up a fund or instrument in the synthetic product universe: asset class, risk "
        "rating, liquidity terms, sectors, leverage and registered jurisdictions."
    ),
    input_schema={
        "type": "object",
        "properties": {
            "instrument_id": {"type": "string", "description": "e.g. 'AGE', 'BPC', 'SAA'"},
        },
        "required": ["instrument_id"],
        "additionalProperties": False,
    },
)
def lookup_instrument(args: dict[str, Any]) -> ToolResult:
    instrument = get_instrument(args["instrument_id"])
    if instrument is None:
        known = ", ".join(sorted(i["instrument_id"] for i in all_instruments()))
        return ToolResult.error(f"Unknown instrument '{args['instrument_id']}'. Known: {known}")
    return ToolResult.ok(
        instrument,
        f"{instrument['name']}, {instrument['asset_class']}, "
        f"risk {instrument['risk_rating']}/7, dealing: {instrument['liquidity']}.",
    )
